version: '3.1'

services:

  wordpress:
    image: wordpress
    restart: always
    ports:
      - 666:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wp_user
      WORDPRESS_DB_PASSWORD: astagfirullah21!
      WORDPRESS_DB_NAME: wp
    volumes:
      - wordpress:/var/www/html
      - ./deploy/wp-content:/var/www/html/wp-content

  db:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: wp
      MYSQL_USER: wp_user
      MYSQL_PASSWORD: astagfirullah21!
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - db:/var/lib/mysql

volumes:
  wordpress:
  db: